### ISSUE TITLE
AWS Keys, SendGrid username and password

### ISSUE THREAD

**Issue by 726973696e6773756e** [jdodson3106/websolutions#1]
Dear Justin, 

Your AWS Keys and Access Code is publically exposed.
https://github.com/jdodson3106/websolutions/blob/9a35358b42af674f104e41d67d61f1690803a967/mysite/settings.py,

Your sendgrid creditals are also on display...

I would suggest resetting your AWS Access Keys and the password to your SendGrid account. In the future please remove your AWS Access Key ID and SendGrid login credentials from the settings before deployment to a public git repostitory. 

Many Thanks
726973696e6773756e

**Comment by jdodson3106** [comment]
Removed from repo and deleted all historic commits.
